### ISSUE TITLE
Any plan to add Prometheus jmx-exporter agent?

### ISSUE THREAD

**Issue by rafaeltuelho** [wildfly/wildfly-s2i#10]
I was trying to get Prometheus jmx-exporter working with `openshift/wildfly-160-centos7` but I got stuck due to some issues with LogManager and OpenJDK 11...

Any plan to add support for this here?

**Comment by jmesnil** [comment]
With WildFly 16, there is a [metrics subsystem](https://docs.wildfly.org/16/Admin_Guide.html#MicroProfile_Metrics_SmallRye) that provides Prometheus metrics  out of the box from `:9990/metrics` endpoint.

With this subsystem, you should no longer need to setup the Prometheus imx-exporter to get metrics from WildFly.

**Comment by rafaeltuelho** [comment]
Awesome! Good to know.

What about this cekit module for prometheus? 
   https://github.com/jboss-openshift/cct_module/tree/master/jboss/container/prometheus

This is used internally?

**Comment by jfdenise** [comment]
Not used by wildfly-s2i. Other projects use these modules.
