### ISSUE TITLE
[S2I v2] Backwards compatibility with existing S2I images

### ISSUE THREAD

**Issue by jmesnil** [wildfly/wildfly-s2i#245]
I'm working on updating the Helm Charts for WildFly to work with the new S2I v2 images.
As much as possible, I want to avoid breaking backwards compatibility of the charts *depending* on the S2I images.

There are 2 required changes:

1. https://github.com/jmesnil/wildfly-charts/commit/646050f8bbde38632b425535244201f098eb2bc6#diff-d88b101c90efd3739b68f0b75d48b9d5c6aec4b9d2c21572581f46a8c0fa11f7

Could we create a symlink from `/opt/server` to `/s2i-output/server`?

2. https://github.com/jmesnil/wildfly-charts/commit/646050f8bbde38632b425535244201f098eb2bc6#diff-c1ab69f7a46b307eaf23e2211c34c0128c767f13c92553ceb8aa408470b1691c

The only real changes is that the existing Dockerfile has a `CMD $JBOSS_HOME/bin/openshift-launch.sh` command.

I'm not sure how we could avoid breaking compatibility here as there is no guarantee that this file would exist in the new S2I images (which afaiu run with the command `sh -c ${JBOSS_CONTAINER_WILDFLY_RUN_MODULE}/run`)

With these 2 caveats, I am able to use the existing released Helm Charts to deploy an application using the new wildfly-maven-plugin and S2I images.

For reference, I'm using this [Helm chart](https://github.com/jmesnil/quickstart/blob/EAP7-1843/helloworld-rs/charts/helm.yaml) to release a `wildfly` app.
And then I have to patch the BuildConfig with this [patch](https://github.com/jmesnil/quickstart/blob/EAP7-1843/helloworld-rs/charts/patch.yaml) by running:

```
oc patch bc wildfly --patch "$(curl https://raw.githubusercontent.com/jmesnil/quickstart/EAP7-1843/helloworld-rs/charts/patch.yaml)"
```

**Comment by bdlink** [comment]
I am trying to write a pom file that will work with the old s2i images as well as the new ones, to run on Openshift (specifically OKD).  If the maven profile used in the s2i were configurable, this would be easy enough, but both versions seem to hard code -Popenshift.  

The old version requires a ROOT.war to be output using the maven-war-plugin (and copies the file to the deployment folder), and the new one uses the wildfly-maven-plugin (and uses wildfly:deploy to deploy it) with runtime-name as ROOT.war

One way or the other, it would be useful to have a pom file that would work for both.

**Comment by jfdenise** [comment]
Closing as we will not fix.
