### ISSUE TITLE
S2i build time WildFly server customization hooks

### ISSUE THREAD

**Issue by ridvan70** [wildfly/wildfly-s2i#28]
Hi,

I've tried to add JTDS driver by following the documentation.

**install.sh is not run at build time.**

I have tried the same on **JBoss EAP** and it **works**:

```
INFO Processing ImageSource mounts: extensions
INFO Processing ImageSource from /tmp/src/extensions
```

I'm using Wildfly 16 image

Regards,
Ridvan

**Comment by jfdenise** [comment]
Hi @ridvan70 , we have added this support to image 17: https://quay.io/wildfly/wildfly-centos7:17.0

**Comment by ridvan70** [comment]
Hi @jfdenise, thanks for the info.

Updating the README with this hint would be very helpful. 
The image stream file suffixes in the section "OpenShift oc usage" must be updated too.
