### ISSUE TITLE
Create multi arch images

### ISSUE THREAD

**Issue by jfdenise** [wildfly/wildfly-s2i#310]
It has been observed on arm platform (Mac), bad performances when using linux/amd64 images.
Although cekit support --platform we are running into some issues:
* https://github.com/cekit/cekit/pull/774 (That would get fixed)
* When using podman, the generated image at the end of the build is stored in local repository and is not multi-arch. Same issue should occur when we will be able to use docker from cekit.

The current solution would be to:
* use cekit to generate the dockerfile
* Use docker buildx build --squash --platform=linux/arm64,linux/amd64 --push -t quay.io/... target/image
* That does push multi arch images to quay.io but squashing is non effective. See: https://github.com/docker/buildx/issues/727

We can release today single arch amd64 images and, in the future, when the best solution is found, push to the same image name multi arch images. Quay.io supports it.

**Comment by galderz** [comment]
FYI, keep an eye on the resolution of https://github.com/quarkusio/quarkus-images/issues/83 for an example on how to do multiarch images with cekit. It's still WIP

**Comment by jfdenise** [comment]
@galderz , thank-you. It seems that we have a similar approach, we do a dry-run then do a docker buildx: https://github.com/wildfly/wildfly-s2i/blob/main/.github/workflows/v2-push.yml#L120 One issue is that squash doesn't actually squash the image.
I noticed that you are not squashing the image. Are you planning to squash to reduce the image size?

**Comment by cescoffier** [comment]
One thing at a time. The size will be important, but it's not a priority for us (Quarkus images) at the moment. We are looking at different approaches to reduce the size, including trying to see how we can use smaller base images (ubi-micro instead of -minimal).

**Comment by jmesnil** [comment]
Another approach would be to use cekit to generate the Dockerfile and `buildah` to build the multiarch images as it seems to support squashing.

https://github.com/redhat-actions/buildah-build/blob/main/.github/workflows/multiarch.yml is an example of a multiarch image with buildah
