### ISSUE TITLE
Error installing example on OKD 4.9

### ISSUE THREAD

**Issue by bdlink** [wildfly/wildfly-s2i#324]
I attempted to run the jsf-ejb-jpa example mentioned in the April 20 news item, https://www.wildfly.org/news/2022/04/20/WildFly-s2i-v2-Released/. Following the instructions on the example's README.md file at https://github.com/wildfly/wildfly-s2i/tree/main/examples/jsf-ejb-jpa, I ran the following:
helm install jsf-ejb-jpa-app -f helm.yaml wildfly/wildfly

Indtead of a successful install, the following error resulted:
Error: INSTALLATION FAILED: chart requires kubeVersion: >= 1.19.0 which is incompatible with Kubernetes v1.22.1-1839+b93fd35dd03051-dirty

Looking at other instances of similar errors for different projects, this may be a problem with the Wildfly helm chart.

My cluster is running v1.22.3+fdba464

oc version
Client Version: 4.10.0-0.okd-2022-03-07-131213
Server Version: 4.9.0-0.okd-2022-02-12-140851
Kubernetes Version: v1.22.1-1839+b93fd35dd03051-dirty

k version
Client Version: version.Info{Major:"1", Minor:"23", GitVersion:"v0.23.0", GitCommit:"f93da17", GitTreeState:"clean", BuildDate:"2022-02-15T22:14:58Z", GoVersion:"go1.17.5", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"22+", GitVersion:"v1.22.1-1839+b93fd35dd03051-dirty", GitCommit:"b93fd35dd030519c24dd02f8bc2a7f873d2928cd", GitTreeState:"dirty", BuildDate:"2022-02-11T06:14:59Z", GoVersion:"go1.16.6", Compiler:"gc", Platform:"linux/amd64"}
WARNING: version difference between client (0.23) and server (1.22) exceeds the supported minor version skew of +/-1

**Comment by jfdenise** [comment]
@bdlink , OKD version adds a -1839. Seems that WildFly chart doesn't handle correctly this format. Helm allows to handle the "pre-release"  (see: https://helm.sh/docs/chart_template_guide/function_list/#working-with-prerelease-versions). @jmesnil WDYT?

**Comment by jmesnil** [comment]
@bdlink Thanks for the report. That's indeed a common issue with `helm`. I've opened an issue to fix that in the WildFly chart: https://github.com/wildfly/wildfly-charts/issues/61

**Comment by jmesnil** [comment]
@bdlink We have released version 2.0.1 of the Helm Chart for WildFly that should fix your issue: https://github.com/wildfly/wildfly-charts/releases/tag/wildfly-2.0.1

Could you please give it a try and verify that you are then able to use it on OKD 4.9?

**Comment by bdlink** [comment]
The change to the wildfly chart (changing the kubernetes version check to ">= 1.19.0-0" in the Chart.yaml) fixed my issue.  I then successfully ran the jaf-ejb-jpa example on OKD 4.9.  (The fix also worked on OKD 4.10).
This issue can be closed.

Thanks for your quick help
Bruce

**Comment by jmesnil** [comment]
@bdlink thanks to you for reporting the issue and verifying it :)
