### ISSUE TITLE
Testing images are pushed to quay.io/wildfly

### ISSUE THREAD

**Issue by jmesnil** [wildfly/wildfly-s2i#360]
In https://github.com/wildfly/wildfly-s2i/commit/02ec52372745b1e694d3d5cca17306c84e3d0052#diff-28802fbf11c83a2eee09623fb192785e7ca92a3f40602a517c011b947a1822d3R123-R124, the `clusterbench` image that is used for testing the WildFly Operator was moved from the `wildlfy-quickstart` to the `wildfly` organization.

I'm not sure that was intentional. The `wildfly` org should contain "official" images for WildFly and I was not expecting to get testing images in there. 
Should we revert to push this clusterbench image to `wildfly-quickstart` ?

**Comment by yersan** [comment]
> Should we revert to push this clusterbench image to wildfly-quickstart ?

I vote for revert and push back to the original location. If that is not finally done, we have to keep the Operator [example](https://github.com/wildfly/wildfly-operator/blob/main/examples/clustering/crds/clusterbench.yaml#L6) in sync with what is expected.

Notice this also affects the [postgresql](https://github.com/wildfly/wildfly-operator/blob/main/examples/postgresql/crds/taskrs-app.yaml#L6) example

**Comment by jfdenise** [comment]
Thank-you, I opened PR https://github.com/wildfly/wildfly-s2i/pull/366. Once re-pushed, I think that we can delete the wrong images located in the wildfly organization.

**Comment by jmesnil** [comment]
I've delete the `wildfly/taskrs-app` and `wildfly/clusterbench` images from quay.io
