### ISSUE TITLE
Use feature pack from a zipped maven repository 

### ISSUE THREAD

**Issue by tommasoborgato** [wildfly/wildfly-s2i#374]
Let's say we have a new version of the server available as a feature pack inside a zipped maven repository, how do we instruct the s2i build (= the builder image) to use such a repository? is it related in anyway to the MAVEN_REPO_URL variable used in the tests?

**Comment by jmesnil** [comment]
There are 2 ways to use a zipped maven repository using S2I builds.

The first one is to deploy the artifacts from the zipped maven repo in a proxy and uses the `MAVEN_REPO_URL` to use this proxy.
The best material for this approach is https://cloud.redhat.com/blog/improving-build-time-java-builds-openshift?extIdCarryOver=true&sc_cid=701f2000001Css5AAC

The second way is to bundle the zipped maven repository in a Docker image and inject it during S2I build.
This approach is simple in theory but requires more plumbing. To achieve it, you need:

* to unzip the zipped Maven repository and put it in a `scratch` Docker image with something like:

```
$ cat Dockerfile
FROM scratch
COPY my-maven-repo /maven-repository
$ docker build -t my-maven-repo .
```

* Push this image to the OpenShift image registry:

```
$ oc registry login
$ docker login -u openshift -p $(oc whoami -t) $OPENSHIFT_IMAGE_REGISTRY
$ docker tag  my-maven-repo $OPENSHIFT_IMAGE_REGISTRY/jmesnil1-dev/my-maven-repo
$ docker push $OPENSHIFT_IMAGE_REGISTRY/jmesnil1-dev/my-maven-repo
```

* In the build config, inject this `my-maven-repo` during the S2I build:

```
    - from:
        kind: ImageStreamTag
        name: 'my-maven-repo:latest'
      paths:
        - sourcePath: /maven-repository
          destinationDir: ./my-maven-repo
```

* and finally use a `settings.xml` that references this repository:

```
                <repository>
                    <id>my-repository</id>
                    <url>file:///tmp/src/my-maven-repo/maven-repository</url>
                </repository>
```

The first approach is less intrusive (but you have to set up a Maven proxy) while the second requires less resources (but more plumbing into the S2I resources)

**Comment by jfdenise** [comment]
@tommasoborgato , this feature could help you too: https://github.com/wildfly/wildfly-s2i/issues/393
This will be enabled for the next WildFly s2i image 1.2.0.Final that should be released soon.
