### ISSUE TITLE
Provide v2 imagestreams for Openshift

### ISSUE THREAD

**Issue by bdlink** [wildfly/wildfly-s2i#380]
At the moment, the only available Openshift image streams are the ones under the "current" branch.  These are installed by default in the OKD version of Openshift.  The corresponding versions in the "main" branch do not seem to exist. 

It would be useful to have the new s2i and base images as well.  Even if the helm usage is available, having the earlier use case of using the Image from the samples operator would be helpful (allows easier configuration of a wildfly application from the console).

At the moment, the OKD image is (and seem set to be) incompatible with the new helm-based build use case.

Given the existence of these imagestreams, ongoing versions of Openshift could continue with them alone, or both the old and new (suitably named).  For backwards compatibility (both versions would be needed).

As part of this enhancement, the README should be updated to cover installation using oc, as is in the "current" branch.

**Comment by jfdenise** [comment]
@bdlink thank-you for your suggestion. As you noticed Helm Chart is what we are advising. We could add image stream files if that opens capabilities. As opposed to the s2i v1 (that contained image stream tag for each WildFly version), we should only need a latest tag for each image (JDK11/JDK17 builder and runtime). They could be located in the main branch. Covering their usage with oc commands would be a nice addition too.
