### ISSUE TITLE
Allow overriding maven profile name so it is not hard coded to "openshift"

### ISSUE THREAD

**Issue by bdlink** [wildfly/wildfly-s2i#381]
At the moment, as has been well recognized, the new version of wildfly-s2i is not backwards compatible.  The new README implies it is possible to change the name of the maven profile used to package the project:
`In order to provision a server during the build phase you must integrate (generally in a profile named openshift profile) an execution of the [WildFly Maven plugin](https://github.com/wildfly/wildfly-maven-plugin/).`

(Usiing "generally" suggests it is not required to be named "openshift")

The documentation does not indicate how to use anything other than "openshift" for the profile name.  If this is possible, the README should indicate how to do it.  If it is not possible, it should be.

For backward compatibility, it would be useful to be able to use one maven profile name for the older s2i case, and another for the new s2i case.  This avoids users needing to have separate application git branches for the two use cases.  It does not really matter whether the older s2i (in the "current" branch here) or the newer one (in the "main" branch) allows this, but I do not find this capability in either version.

**Comment by jfdenise** [comment]
@bdlink , we have addressed backward compatibility with the use of `GALLEON_PROVISION_FEATURE_PACKS/GALLEON_PROVISION_LAYERS` env variables. So the v2 image can be used to build existing WildFly applications. Would that work for your use-case?

For dual project, you could have the new approach based on the WildFly maven plugin in the "openshift" (default profile) and when building the legacy set `MAVEN_ARGS=-Pmycustomprofile -DskipTests` This should work.

**Comment by bdlink** [comment]
@jfdenise, using the MAVEN_ARGS to change the profile on the openshift imagestream does indeed work.  It is an extra manual step for using the existing openshift imagestream (which is v1 only), it is a reasonable workaround that allows progressing to the newer workflow.

Thanks, Bruce
