### ISSUE TITLE
Provides a single builder image that can support multiple JDK versions

### ISSUE THREAD

**Issue by jmesnil** [wildfly/wildfly-s2i#401]
Currently, we have 1 builder image per JDK version.

If we want to provide additional JDK version (eg for non-LTS releases such as JDK 19), we have to add a new image for it.

As the builder image is used to build the application and provision WildFly, I wonder if we could have single builder image that provides multiple JDK versions and let users chose the one they want.
With that way, we could have 1 single builder image. We would still have 1 runtime image per JDK version.

Something to consider is that the image built from the builder image is executable (even though we do not recommend to use it).
The built image would be significantly bigger and we would need to make sure that the JDK version used to build the application is also used to run the server when the image is run.

**Comment by jfdenise** [comment]
That is something that we are not going to address.
