### ISSUE TITLE
no tag v27.0 in github

### ISSUE THREAD

**Issue by gaol** [wildfly/wildfly-s2i#416]
Some wildfly quickstarts need to be verified with WildFly 27, some links like in [ejb-txn-remote-call quickstarts](https://github.com/wildfly/quickstart/blob/main/ejb-txn-remote-call/README.adoc#running-on-openshift-build-the-application) are:

```
# Install builder image streams
oc create -f {ImageandTemplateImportURL}imagestreams/wildfly-centos7.json
# Install runtime image streams
oc create -f {ImageandTemplateImportURL}imagestreams/wildfly-runtime-centos7.json

# Deploy template with chain build to get the quickstart
# being deployed within runtime image
oc create -f {ImageandTemplateImportURL}templates/wildfly-s2i-chained-build-template.yml
```

The  `{ImageandTemplateImportURL}` in main branch of [quickstart](https://github.com/wildfly/quickstart/tree/main) is interpreted as `https://raw.githubusercontent.com/wildfly/wildfly-s2i/v27.0/`, and there is no such tag in this repository.

and please also advice which files need to be used if the `wildfly-*.json` files and the chained build template yaml file in `v27.0` won't apply anymore. thanks.

**Comment by gaol** [comment]
Thanks @jfdenise for the info, I am actually working on the issue of verifying and re-enable the `ejb-txn-remote-call` [quickstart](https://issues.redhat.com/browse/WFLY-17399), I will read more on the helloword one. :)

**Comment by jfdenise** [comment]
@gaol , we don't need such tag. Use the latest image: `quay.io/wildfly/wildfly-s2i:latest`, WildFly 27.0.x.Final feature-pack and cloud feature-pack 2.0.x.Final as shown in this example: https://github.com/wildfly/wildfly-s2i/blob/main/examples/web-clustering/pom.xml#L40
