### ISSUE TITLE
RFE: add `tar` to the runtime image to be able to perform `kubectl cp`

### ISSUE THREAD

**Issue by jmesnil** [wildfly/wildfly-s2i#487]
While working on https://github.com/jmesnil/kubectl-jboss-cli, I found that I could not use `kubectl cp` to push a file to a container before I can execute it with the WildFly CLI console.

I opened https://github.com/jmesnil/kubectl-jboss-cli/issues/2 that would be solved by adding `tar` RPM to the runtime image.

**Comment by jmesnil** [comment]
@jfdenise I tested that it works with the image at https://quay.io/repository/wildfly-snapshots/wildfly-runtime. thanks!

**Comment by jfdenise** [comment]
@jmesnil , thank-you. New  images have been released.
